import useKaikas from '@hooks/useKaikas';
import useMetamask from '@hooks/useMetamask'
import ethereumContractABI from '@utils/contracts/metamask/abi';
// import ethereumContractBytecode from '@utils/contracts/metamask/bytecode';
import type { NextPage } from 'next'
import { useEffect } from 'react';

const Home: NextPage = () => {
  const { connect, deployContract, callContract, selectedAddress } = useMetamask();
  const {  } = useKaikas();
  useEffect(() => {
    (async () => {
      await connect();
      if (!selectedAddress) return;
      await callContract({from: selectedAddress, abi: ethereumContractABI, contractAddress: '0xA52a2382C25a44A2e833A533C1E85439398e075e', methodName: 'setSaleInfo', args: [1664899200,
        1665777600,
        10000,
        1000,
        2,
        10,
        5,
        1,]});
    })()
  }, [connect, callContract, selectedAddress])

  useEffect(() => {
  }, [])

  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
